"""
Read `.eig` files generated by `pw2wannier90.x`, 
or maybe `sig2wan`.
"""
function read_wannier_eig(path, nbnd, nkp)
    bands_data = readlines(path)
    bands_data = map(bands_data) do line
        parse(Float64, split(line)[3]) 
    end
    bands_data = reshape(bands_data, (nbnd, nkp))
end