"""
Parse `eqp` files generated by `sigma`. 
"""
function read_bgw_eqp(path)
    data = readlines(path)
    nbnd = parse(Int, split(data[1])[4])
    nkp = Int(length(data) / (nbnd + 1))
    
    kpoints = data[1 : nbnd + 1 : end]
    kpoints = map(kpoints) do line
        map(split(line)[1:3]) do x
            parse(Float64, x)
        end
    end
    kpoints = hcat(kpoints...)
    
    deleteat!(data, 1 : nbnd + 1 : length(data))
    data = reshape(data, (nbnd, nkp))
    dft_bands = map(data) do line
        parse(Float64, split(line)[3])
    end
    gw_bands = map(data) do line
        parse(Float64, split(line)[4])
    end
    cat(dft_bands, gw_bands, dims = 3)
end